# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.dialogflow_cx_v3beta1.proto import (
    environment_pb2 as google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2,
)
from google.longrunning import (
    operations_pb2 as google_dot_longrunning_dot_operations__pb2,
)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EnvironmentsStub(object):
    """Service for managing [Environments][google.cloud.dialogflow.cx.v3beta1.Environment].
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEnvironments = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/ListEnvironments",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsResponse.FromString,
        )
        self.GetEnvironment = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/GetEnvironment",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.GetEnvironmentRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.Environment.FromString,
        )
        self.CreateEnvironment = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/CreateEnvironment",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )
        self.UpdateEnvironment = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/UpdateEnvironment",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.UpdateEnvironmentRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )
        self.DeleteEnvironment = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/DeleteEnvironment",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.DeleteEnvironmentRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.LookupEnvironmentHistory = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Environments/LookupEnvironmentHistory",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryResponse.FromString,
        )


class EnvironmentsServicer(object):
    """Service for managing [Environments][google.cloud.dialogflow.cx.v3beta1.Environment].
    """

    def ListEnvironments(self, request, context):
        """Returns the list of all environments in the specified [Agent][google.cloud.dialogflow.cx.v3beta1.Agent].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEnvironment(self, request, context):
        """Retrieves the specified [Environment][google.cloud.dialogflow.cx.v3beta1.Environment].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateEnvironment(self, request, context):
        """Creates an [Environment][google.cloud.dialogflow.cx.v3beta1.Environment] in the specified [Agent][google.cloud.dialogflow.cx.v3beta1.Agent].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateEnvironment(self, request, context):
        """Updates the specified [Environment][google.cloud.dialogflow.cx.v3beta1.Environment].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteEnvironment(self, request, context):
        """Deletes the specified [Environment][google.cloud.dialogflow.cx.v3beta1.Environment].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LookupEnvironmentHistory(self, request, context):
        """Looks up the history of the specified [Environment][google.cloud.dialogflow.cx.v3beta1.Environment].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EnvironmentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListEnvironments": grpc.unary_unary_rpc_method_handler(
            servicer.ListEnvironments,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsResponse.SerializeToString,
        ),
        "GetEnvironment": grpc.unary_unary_rpc_method_handler(
            servicer.GetEnvironment,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.GetEnvironmentRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.Environment.SerializeToString,
        ),
        "CreateEnvironment": grpc.unary_unary_rpc_method_handler(
            servicer.CreateEnvironment,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.CreateEnvironmentRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
        "UpdateEnvironment": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateEnvironment,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.UpdateEnvironmentRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
        "DeleteEnvironment": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteEnvironment,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.DeleteEnvironmentRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "LookupEnvironmentHistory": grpc.unary_unary_rpc_method_handler(
            servicer.LookupEnvironmentHistory,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.dialogflow.cx.v3beta1.Environments", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Environments(object):
    """Service for managing [Environments][google.cloud.dialogflow.cx.v3beta1.Environment].
    """

    @staticmethod
    def ListEnvironments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/ListEnvironments",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetEnvironment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/GetEnvironment",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.GetEnvironmentRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.Environment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreateEnvironment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/CreateEnvironment",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateEnvironment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/UpdateEnvironment",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.UpdateEnvironmentRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteEnvironment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/DeleteEnvironment",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.DeleteEnvironmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def LookupEnvironmentHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Environments/LookupEnvironmentHistory",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_environment__pb2.LookupEnvironmentHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
