# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow_cx_v3beta1/proto/fulfillment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.cloud.dialogflow_cx_v3beta1.proto import (
    response_message_pb2 as google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_response__message__pb2,
)
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="google/cloud/dialogflow_cx_v3beta1/proto/fulfillment.proto",
    package="google.cloud.dialogflow.cx.v3beta1",
    syntax="proto3",
    serialized_options=b'\n&com.google.cloud.dialogflow.cx.v3beta1B\020FulfillmentProtoP\001ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/cx/v3beta1;cx\370\001\001\242\002\002DF\252\002"Google.Cloud.Dialogflow.Cx.V3Beta1',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n:google/cloud/dialogflow_cx_v3beta1/proto/fulfillment.proto\x12"google.cloud.dialogflow.cx.v3beta1\x1a\x19google/api/resource.proto\x1a?google/cloud/dialogflow_cx_v3beta1/proto/response_message.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto"\xe4\x06\n\x0b\x46ulfillment\x12\x45\n\x08messages\x18\x01 \x03(\x0b\x32\x33.google.cloud.dialogflow.cx.v3beta1.ResponseMessage\x12\x37\n\x07webhook\x18\x02 \x01(\tB&\xfa\x41#\n!dialogflow.googleapis.com/Webhook\x12\x0b\n\x03tag\x18\x03 \x01(\t\x12\x61\n\x15set_parameter_actions\x18\x04 \x03(\x0b\x32\x42.google.cloud.dialogflow.cx.v3beta1.Fulfillment.SetParameterAction\x12[\n\x11\x63onditional_cases\x18\x05 \x03(\x0b\x32@.google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases\x1aN\n\x12SetParameterAction\x12\x11\n\tparameter\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\x1a\xb7\x03\n\x10\x43onditionalCases\x12T\n\x05\x63\x61ses\x18\x01 \x03(\x0b\x32\x45.google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case\x1a\xcc\x02\n\x04\x43\x61se\x12\x11\n\tcondition\x18\x01 \x01(\t\x12g\n\x0c\x63\x61se_content\x18\x02 \x03(\x0b\x32Q.google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent\x1a\xc7\x01\n\x0b\x43\x61seContent\x12\x46\n\x07message\x18\x01 \x01(\x0b\x32\x33.google.cloud.dialogflow.cx.v3beta1.ResponseMessageH\x00\x12\\\n\x10\x61\x64\x64itional_cases\x18\x02 \x01(\x0b\x32@.google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCasesH\x00\x42\x12\n\x10\x63\x61ses_or_messageB\xaf\x01\n&com.google.cloud.dialogflow.cx.v3beta1B\x10\x46ulfillmentProtoP\x01ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/cx/v3beta1;cx\xf8\x01\x01\xa2\x02\x02\x44\x46\xaa\x02"Google.Cloud.Dialogflow.Cx.V3Beta1b\x06proto3',
    dependencies=[
        google_dot_api_dot_resource__pb2.DESCRIPTOR,
        google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_response__message__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,
        google_dot_api_dot_annotations__pb2.DESCRIPTOR,
    ],
)


_FULFILLMENT_SETPARAMETERACTION = _descriptor.Descriptor(
    name="SetParameterAction",
    full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.SetParameterAction",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="parameter",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.SetParameterAction.parameter",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.SetParameterAction.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=599,
    serialized_end=677,
)

_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT = _descriptor.Descriptor(
    name="CaseContent",
    full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent.message",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="additional_cases",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent.additional_cases",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="cases_or_message",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent.cases_or_message",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=920,
    serialized_end=1119,
)

_FULFILLMENT_CONDITIONALCASES_CASE = _descriptor.Descriptor(
    name="Case",
    full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="condition",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.condition",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="case_content",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.case_content",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT,],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=787,
    serialized_end=1119,
)

_FULFILLMENT_CONDITIONALCASES = _descriptor.Descriptor(
    name="ConditionalCases",
    full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="cases",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.cases",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[_FULFILLMENT_CONDITIONALCASES_CASE,],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=680,
    serialized_end=1119,
)

_FULFILLMENT = _descriptor.Descriptor(
    name="Fulfillment",
    full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="messages",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.messages",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="webhook",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.webhook",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\372A#\n!dialogflow.googleapis.com/Webhook",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tag",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.tag",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="set_parameter_actions",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.set_parameter_actions",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="conditional_cases",
            full_name="google.cloud.dialogflow.cx.v3beta1.Fulfillment.conditional_cases",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[_FULFILLMENT_SETPARAMETERACTION, _FULFILLMENT_CONDITIONALCASES,],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=251,
    serialized_end=1119,
)

_FULFILLMENT_SETPARAMETERACTION.fields_by_name[
    "value"
].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_FULFILLMENT_SETPARAMETERACTION.containing_type = _FULFILLMENT
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name[
    "message"
].message_type = (
    google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_response__message__pb2._RESPONSEMESSAGE
)
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name[
    "additional_cases"
].message_type = _FULFILLMENT_CONDITIONALCASES
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.containing_type = (
    _FULFILLMENT_CONDITIONALCASES_CASE
)
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.oneofs_by_name[
    "cases_or_message"
].fields.append(
    _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name["message"]
)
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name[
    "message"
].containing_oneof = _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.oneofs_by_name[
    "cases_or_message"
]
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.oneofs_by_name[
    "cases_or_message"
].fields.append(
    _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name["additional_cases"]
)
_FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.fields_by_name[
    "additional_cases"
].containing_oneof = _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT.oneofs_by_name[
    "cases_or_message"
]
_FULFILLMENT_CONDITIONALCASES_CASE.fields_by_name[
    "case_content"
].message_type = _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT
_FULFILLMENT_CONDITIONALCASES_CASE.containing_type = _FULFILLMENT_CONDITIONALCASES
_FULFILLMENT_CONDITIONALCASES.fields_by_name[
    "cases"
].message_type = _FULFILLMENT_CONDITIONALCASES_CASE
_FULFILLMENT_CONDITIONALCASES.containing_type = _FULFILLMENT
_FULFILLMENT.fields_by_name[
    "messages"
].message_type = (
    google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_response__message__pb2._RESPONSEMESSAGE
)
_FULFILLMENT.fields_by_name[
    "set_parameter_actions"
].message_type = _FULFILLMENT_SETPARAMETERACTION
_FULFILLMENT.fields_by_name[
    "conditional_cases"
].message_type = _FULFILLMENT_CONDITIONALCASES
DESCRIPTOR.message_types_by_name["Fulfillment"] = _FULFILLMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fulfillment = _reflection.GeneratedProtocolMessageType(
    "Fulfillment",
    (_message.Message,),
    {
        "SetParameterAction": _reflection.GeneratedProtocolMessageType(
            "SetParameterAction",
            (_message.Message,),
            {
                "DESCRIPTOR": _FULFILLMENT_SETPARAMETERACTION,
                "__module__": "google.cloud.dialogflow_cx_v3beta1.proto.fulfillment_pb2",
                "__doc__": """Setting a parameter value.
    
    Attributes:
        parameter:
            Display name of the parameter.
        value:
            The new value of the parameter. A null value clears the
            parameter.
    """,
                # @@protoc_insertion_point(class_scope:google.cloud.dialogflow.cx.v3beta1.Fulfillment.SetParameterAction)
            },
        ),
        "ConditionalCases": _reflection.GeneratedProtocolMessageType(
            "ConditionalCases",
            (_message.Message,),
            {
                "Case": _reflection.GeneratedProtocolMessageType(
                    "Case",
                    (_message.Message,),
                    {
                        "CaseContent": _reflection.GeneratedProtocolMessageType(
                            "CaseContent",
                            (_message.Message,),
                            {
                                "DESCRIPTOR": _FULFILLMENT_CONDITIONALCASES_CASE_CASECONTENT,
                                "__module__": "google.cloud.dialogflow_cx_v3beta1.proto.fulfillment_pb2",
                                "__doc__": """The list of messages or conditional cases to activate for this case.
        
        Attributes:
            cases_or_message:
                Either a message is returned or additional cases to be
                evaluated.
            message:
                Returned message.
            additional_cases:
                Additional cases to be evaluated.
        """,
                                # @@protoc_insertion_point(class_scope:google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case.CaseContent)
                            },
                        ),
                        "DESCRIPTOR": _FULFILLMENT_CONDITIONALCASES_CASE,
                        "__module__": "google.cloud.dialogflow_cx_v3beta1.proto.fulfillment_pb2",
                        "__doc__": """Each case has a Boolean condition. When it is evaluated to be True,
      the corresponding messages will be selected and evaluated recursively.
      
      Attributes:
          condition:
              The condition to activate and select this case. Empty means
              the condition is always true. The condition is evaluated
              against [form parameters][Form.parameters] or [session
              parameters][SessionInfo.parameters].  See the `conditions
              reference <https://cloud.google.com/dialogflow/cx/docs/referen
              ce/condition>`__.
          case_content:
              A list of case content.
      """,
                        # @@protoc_insertion_point(class_scope:google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases.Case)
                    },
                ),
                "DESCRIPTOR": _FULFILLMENT_CONDITIONALCASES,
                "__module__": "google.cloud.dialogflow_cx_v3beta1.proto.fulfillment_pb2",
                "__doc__": """A list of cascading if-else conditions. Cases are mutually exclusive.
    The first one with a matching condition is selected, all the rest
    ignored.
    
    Attributes:
        cases:
            A list of cascading if-else conditions.
    """,
                # @@protoc_insertion_point(class_scope:google.cloud.dialogflow.cx.v3beta1.Fulfillment.ConditionalCases)
            },
        ),
        "DESCRIPTOR": _FULFILLMENT,
        "__module__": "google.cloud.dialogflow_cx_v3beta1.proto.fulfillment_pb2",
        "__doc__": """A fulfillment can do one or more of the following actions at the same
  time:  -  Generate rich message responses. -  Set parameter values. -
  Call the webhook.  Fulfillments can be called at various stages in the
  [Page][google.cloud.dialogflow.cx.v3beta1.Page] or
  [Form][google.cloud.dialogflow.cx.v3beta1.Form] lifecycle. For
  example, when a [DetectIntentRequest][google.cloud.dialogflow.cx.v3bet
  a1.DetectIntentRequest] drives a session to enter a new page, the
  page’s entry fulfillment can add a static response to the
  [QueryResult][google.cloud.dialogflow.cx.v3beta1.QueryResult] in the
  returning [DetectIntentResponse][google.cloud.dialogflow.cx.v3beta1.De
  tectIntentResponse], call the webhook (for example, to load user data
  from a database), or both.
  
  Attributes:
      messages:
          The list of rich message responses to present to the user.
      webhook:
          The webhook to call. Format: ``projects/<Project
          ID>/locations/<Location ID>/agents/<Agent
          ID>/webhooks/<Webhook ID>``.
      tag:
          The tag used by the webhook to identify which fulfillment is
          being called. This field is required if ``webhook`` is
          specified.
      set_parameter_actions:
          Set parameter values before executing the webhook.
      conditional_cases:
          Conditional cases for this fulfillment.
  """,
        # @@protoc_insertion_point(class_scope:google.cloud.dialogflow.cx.v3beta1.Fulfillment)
    },
)
_sym_db.RegisterMessage(Fulfillment)
_sym_db.RegisterMessage(Fulfillment.SetParameterAction)
_sym_db.RegisterMessage(Fulfillment.ConditionalCases)
_sym_db.RegisterMessage(Fulfillment.ConditionalCases.Case)
_sym_db.RegisterMessage(Fulfillment.ConditionalCases.Case.CaseContent)


DESCRIPTOR._options = None
_FULFILLMENT.fields_by_name["webhook"]._options = None
# @@protoc_insertion_point(module_scope)
