# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow_cx_v3beta1/proto/ivr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="google/cloud/dialogflow_cx_v3beta1/proto/ivr.proto",
    package="google.cloud.dialogflow.cx.v3beta1",
    syntax="proto3",
    serialized_options=b'\n&com.google.cloud.dialogflow.cx.v3beta1B\035InteractiveVoiceResponseProtoP\001ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/cx/v3beta1;cx\370\001\001\242\002\002DF\252\002"Google.Cloud.Dialogflow.Cx.V3Beta1',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n2google/cloud/dialogflow_cx_v3beta1/proto/ivr.proto\x12"google.cloud.dialogflow.cx.v3beta1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/api/annotations.protoB\xbc\x01\n&com.google.cloud.dialogflow.cx.v3beta1B\x1dInteractiveVoiceResponseProtoP\x01ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/cx/v3beta1;cx\xf8\x01\x01\xa2\x02\x02\x44\x46\xaa\x02"Google.Cloud.Dialogflow.Cx.V3Beta1b\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,
        google_dot_api_dot_annotations__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
