# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.dialogflow_cx_v3beta1.proto import (
    version_pb2 as google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2,
)
from google.longrunning import (
    operations_pb2 as google_dot_longrunning_dot_operations__pb2,
)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class VersionsStub(object):
    """Service for managing [Versions][google.cloud.dialogflow.cx.v3beta1.Version].
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListVersions = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/ListVersions",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsResponse.FromString,
        )
        self.GetVersion = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/GetVersion",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.GetVersionRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.FromString,
        )
        self.CreateVersion = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/CreateVersion",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.CreateVersionRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )
        self.UpdateVersion = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/UpdateVersion",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.UpdateVersionRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.FromString,
        )
        self.DeleteVersion = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/DeleteVersion",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.DeleteVersionRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.LoadVersion = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Versions/LoadVersion",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.LoadVersionRequest.SerializeToString,
            response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )


class VersionsServicer(object):
    """Service for managing [Versions][google.cloud.dialogflow.cx.v3beta1.Version].
    """

    def ListVersions(self, request, context):
        """Returns the list of all versions in the specified [Flow][google.cloud.dialogflow.cx.v3beta1.Flow].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetVersion(self, request, context):
        """Retrieves the specified [Version][google.cloud.dialogflow.cx.v3beta1.Version].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateVersion(self, request, context):
        """Creates a [Version][google.cloud.dialogflow.cx.v3beta1.Version] in the specified [Flow][google.cloud.dialogflow.cx.v3beta1.Flow].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateVersion(self, request, context):
        """Updates the specified [Version][google.cloud.dialogflow.cx.v3beta1.Version].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteVersion(self, request, context):
        """Deletes the specified [Version][google.cloud.dialogflow.cx.v3beta1.Version].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LoadVersion(self, request, context):
        """Loads a specified version to draft version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VersionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListVersions": grpc.unary_unary_rpc_method_handler(
            servicer.ListVersions,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsResponse.SerializeToString,
        ),
        "GetVersion": grpc.unary_unary_rpc_method_handler(
            servicer.GetVersion,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.GetVersionRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.SerializeToString,
        ),
        "CreateVersion": grpc.unary_unary_rpc_method_handler(
            servicer.CreateVersion,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.CreateVersionRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
        "UpdateVersion": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateVersion,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.UpdateVersionRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.SerializeToString,
        ),
        "DeleteVersion": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteVersion,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.DeleteVersionRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "LoadVersion": grpc.unary_unary_rpc_method_handler(
            servicer.LoadVersion,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.LoadVersionRequest.FromString,
            response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.dialogflow.cx.v3beta1.Versions", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Versions(object):
    """Service for managing [Versions][google.cloud.dialogflow.cx.v3beta1.Version].
    """

    @staticmethod
    def ListVersions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/ListVersions",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/GetVersion",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.GetVersionRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreateVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/CreateVersion",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.CreateVersionRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/UpdateVersion",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.UpdateVersionRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.Version.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/DeleteVersion",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.DeleteVersionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def LoadVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Versions/LoadVersion",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_version__pb2.LoadVersionRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
