# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.dialogflow_cx_v3beta1.proto import (
    webhook_pb2 as google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2,
)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class WebhooksStub(object):
    """Service for managing [Webhooks][google.cloud.dialogflow.cx.v3beta1.Webhook].
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWebhooks = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/ListWebhooks",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksResponse.FromString,
        )
        self.GetWebhook = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/GetWebhook",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.GetWebhookRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
        )
        self.CreateWebhook = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/CreateWebhook",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.CreateWebhookRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
        )
        self.UpdateWebhook = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/UpdateWebhook",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.UpdateWebhookRequest.SerializeToString,
            response_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
        )
        self.DeleteWebhook = channel.unary_unary(
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/DeleteWebhook",
            request_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.DeleteWebhookRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class WebhooksServicer(object):
    """Service for managing [Webhooks][google.cloud.dialogflow.cx.v3beta1.Webhook].
    """

    def ListWebhooks(self, request, context):
        """Returns the list of all webhooks in the specified agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWebhook(self, request, context):
        """Retrieves the specified webhook.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateWebhook(self, request, context):
        """Creates a webhook in the specified agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateWebhook(self, request, context):
        """Updates the specified webhook.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteWebhook(self, request, context):
        """Deletes the specified webhook.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WebhooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListWebhooks": grpc.unary_unary_rpc_method_handler(
            servicer.ListWebhooks,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksResponse.SerializeToString,
        ),
        "GetWebhook": grpc.unary_unary_rpc_method_handler(
            servicer.GetWebhook,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.GetWebhookRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.SerializeToString,
        ),
        "CreateWebhook": grpc.unary_unary_rpc_method_handler(
            servicer.CreateWebhook,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.CreateWebhookRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.SerializeToString,
        ),
        "UpdateWebhook": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateWebhook,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.UpdateWebhookRequest.FromString,
            response_serializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.SerializeToString,
        ),
        "DeleteWebhook": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteWebhook,
            request_deserializer=google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.DeleteWebhookRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "google.cloud.dialogflow.cx.v3beta1.Webhooks", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Webhooks(object):
    """Service for managing [Webhooks][google.cloud.dialogflow.cx.v3beta1.Webhook].
    """

    @staticmethod
    def ListWebhooks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/ListWebhooks",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.ListWebhooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetWebhook(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/GetWebhook",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.GetWebhookRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreateWebhook(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/CreateWebhook",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.CreateWebhookRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateWebhook(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/UpdateWebhook",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.UpdateWebhookRequest.SerializeToString,
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteWebhook(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/google.cloud.dialogflow.cx.v3beta1.Webhooks/DeleteWebhook",
            google_dot_cloud_dot_dialogflow__cx__v3beta1_dot_proto_dot_webhook__pb2.DeleteWebhookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
